name: AXERA

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9

jobs:
  x86_axcl_builds:
    runs-on: ubuntu-22.04
    name: x86_AXCL Build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set x86_AXCL_TAG
        run: echo "x86_AXCL_TAG=x86-axcl-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set Version
        run: make version

      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          push: false
          targets: x86-axcl
          files: docker/axcl/x86-axcl.hcl
          no-cache: true
          set: |
            x86-axcl.tags=frigate:${{ env.x86_AXCL_TAG }}

      - name: Clean up disk space
        run: |
          docker system prune -f

      - name: Save Docker image as tar file
        run: |
          docker save frigate:${{ env.x86_AXCL_TAG }} -o frigate-${{ env.x86_AXCL_TAG }}.tar
          ls -lh frigate-${{ env.x86_AXCL_TAG }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86-axcl-docker-image
          path: frigate-${{ env.x86_AXCL_TAG }}.tar
          retention-days: 7

  rk_axcl_builds:
    runs-on: ubuntu-22.04-arm
    name: rk_AXCL Build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set RK_AXCL_TAG
        run: echo "RK_AXCL_TAG=rk-axcl-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set Version
        run: make version

      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          push: false
          targets: rk-axcl
          files: |
            docker/rockchip/rk.hcl
            docker/axcl/rk-axcl.hcl
          no-cache: true
          set: |
            rk-axcl.tags=frigate:${{ env.RK_AXCL_TAG }}

      - name: Clean up disk space
        run: |
          docker system prune -f

      - name: Save Docker image as tar file
        run: |
          docker save frigate:${{ env.RK_AXCL_TAG }} -o frigate-${{ env.RK_AXCL_TAG }}.tar
          ls -lh frigate-${{ env.RK_AXCL_TAG }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: rk-axcl-docker-image
          path: frigate-${{ env.RK_AXCL_TAG }}.tar
          retention-days: 7


  rpi_axcl_builds:
    runs-on: ubuntu-22.04-arm
    name: RPi_AXCL Build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set RPi_AXCL_TAG
        run: echo "RPi_AXCL_TAG=rpi-axcl-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set Version
        run: make version

      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          push: false
          targets: rpi-axcl
          files: |
            docker/rpi/rpi.hcl
            docker/axcl/rpi-axcl.hcl
          no-cache: true
          set: |
            rpi-axcl.tags=frigate:${{ env.RPi_AXCL_TAG }}

      - name: Clean up disk space
        run: |
          docker system prune -f

      - name: Save Docker image as tar file
        run: |
          docker save frigate:${{ env.RPi_AXCL_TAG }} -o frigate-${{ env.RPi_AXCL_TAG }}.tar
          ls -lh frigate-${{ env.RPi_AXCL_TAG }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpi-axcl-docker-image
          path: frigate-${{ env.RPi_AXCL_TAG }}.tar
          retention-days: 7
